version: "3.3"

services:
  master:
    build: .
    image: blender
    environment:
      - RENDER_MODE=MASTER
    expose:
      - "8000"
    ports:
      - "80:8000"

  slave:
    build: .
    image: blender
    environment:
      - MASTER_IP=master
      - RENDER_MODE=SLAVE
    links:
      - master
