version: "3.3"

services:
  master:
    build: .
    image: golyalpha/blender
    environment:
      - RENDER_MODE=MASTER
    expose:
      - "8000"
    ports:
      - "80:8000"
    restart: always

  slave:
    build: .
    image: golyalpha/blender
    environment:
      - MASTER_IP=master
      - RENDER_MODE=SLAVE
    links:
      - master
    restart: always
